version: '3.8'

services:
  postgres:
    image: ghcr.io/dilipbam/saahitt-postgres:latest
    environment:
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  customer:
    image: ghcr.io/dobaato/saahitt-customer:latest
    ports:
      - "8001:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:root123@postgres:5432/sahasahit

  venue:
    image: ghcr.io/dobaato/saahitt-venue:latest
    ports:
      - "8002:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:root123@postgres:5432/sahasahit

  super_admin:
    image: ghcr.io/dobaato/saahitt-super_admin:latest
    ports:
      - "8003:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:root123@postgres:5432/sahasahit

volumes:
  postgres_data:
