version: '3.8'

services:
  customer_app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.customer
    image: diliipbam/customer_app:latest
    ports:
      - "8081:80"
    environment:
      - ENV_VAR=value
    depends_on:
      - postgres
      - redis

  venue_app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.vendor
    image: diliipbam/venue_app:latest
    ports:
      - "8082:80"
    environment:
      - ENV_VAR=value
    depends_on:
      - postgres
      - redis

  superadmin:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.superadmin
    image: diliipbam/superadmin:latest
    ports:
      - "8083:80"
    environment:
      - ENV_VAR=value
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
