version: '3.8'

services:
  customer_app:
    image: diliipbam/test:latest
    container_name: customer_app
    environment:
      SERVICE: customer_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sahasahit
      TZ: Asia/Kathmandu
    ports:
      - 8002:9002
    expose:
      - "8000"
    command: ["python", "/app/customer_app/app_customer.py"]
    depends_on:
      - postgres
      - redis
    volumes:
      - ./customer_app:/app/customer_app

  vendor_app:
    image: diliipbam/test:latest
    container_name: vendor_app
    environment:
      SERVICE: vendor_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sahasahit
      TZ: Asia/Kathmandu
    ports:
      - 8001:9001
    expose:
      - "8001"
    command: ["python", "/app/vendor_app/app_vendor.py"]
    depends_on:
      - postgres
      - redis
    volumes:
      - ./vendor_app:/app/vendor_app

  superadmin:
    image: diliipbam/test:latest
    container_name: superadmin
    environment:
      SERVICE: superadmin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sahasahit
      TZ: Asia/Kathmandu
    ports:
      - 8003:9003
    expose:
      - "8003"
    command: ["python", "/app/super_admin/admin_app.py"]
    depends_on:
      - postgres
      - redis
    volumes:
      - ./super_admin:/app/super_admin

  cron_app:
    image: diliipbam/test:latest
    container_name: cron_app
    environment:
      SERVICE: superadmin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sahasahit
      TZ: Asia/Kathmandu
    ports:
      - 8008:9008
    expose:
      - "8008"
    command: ["python", "/app/cron/run_cron.py"]
    depends_on:
      - postgres
      - redis
    volumes:
      - ./cron_app:/app/cron_app

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sahasahit
      TZ: Asia/Kathmandu
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.4
    container_name: redis
    environment:
      - TZ=Asia/Kathmandu
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
  redis_data:
