SPACES = 'spaces'
USERS = 'users'
SUPER_ADMIN = 'super_admin'
CONSUMER_PROFILE = 'consumer_profile'
VENDOR_PROFILE = 'vendor_profile'
FREELANCE = 'freelance'
ORGANIZATION = 'organization'
VENUES = 'venues'
CATERING_PACKAGE = 'catering_package'
ITEMS = 'items'
BOOKINGS = 'bookings'
INVOICE = 'invoice'
VENDOR_INDUSTRY = 'vendor_industry'
VENUE_TYPES = 'venue_types'
USER_TYPE = 'user_type'
VENUE_BOOKINGS = 'venue_bookings'
FOOD_ITEMS = 'food_items'
MENU = 'menu'
MENU_FOOD_ITEMS = 'menu_food_items'
USER_LOGS = 'user_logs'
CONSUMER_ACTIVITY_LOG = 'consumer_activity_log'
VENDOR_ACTIVITY_LOG = 'vendor_activity_log'
CRON_LOG = 'cron_log'
VENDOR_DYNAMIC_FORM = 'vendor_dynamic_form'

# Subscriptions, albums models

SUBSCRIPTION = 'subscription'
IMAGE = 'image'
ALBUM = 'album'
VENDOR_SUBSCRIPTION = 'vendor_subscription'
SHIFTS = 'shifts'
SCHEDULE = 'schedule'
AVAILABILITY = 'availability'
