# customer_app/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY saahit-test/vendor_app /app/vendor_app

COPY saahit-test/vendor_app/.env /app/vendor_app/.env
