FROM python:3.9-slim

# Setting working directory
WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY customer_app /app/customer_app
COPY customer_app/.env /app/customer_app/.env
