# customer_app/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY saahit-test/cron /app/cron

COPY saahit-test/cron/.env /app/cron/.env
